// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgI9E3q9kHDiVd8x6zKc9NBULwJ38OfZM',
    appId: '1:875861037228:web:76b1685f0bd30767ff8f09',
    messagingSenderId: '875861037228',
    projectId: 'chat-app-bffb8',
    authDomain: 'chat-app-bffb8.firebaseapp.com',
    storageBucket: 'chat-app-bffb8.appspot.com',
    measurementId: 'G-G29DVJ28NW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgDo-uQvvgAY5oNcQ6c7Vk1VC0E-dprdk',
    appId: '1:875861037228:android:c89e882f9f29080aff8f09',
    messagingSenderId: '875861037228',
    projectId: 'chat-app-bffb8',
    storageBucket: 'chat-app-bffb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIZSOTXOHRjnhQK7Uf0YCeWggMp2m8TYI',
    appId: '1:875861037228:ios:8972291f80c63bb2ff8f09',
    messagingSenderId: '875861037228',
    projectId: 'chat-app-bffb8',
    storageBucket: 'chat-app-bffb8.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIZSOTXOHRjnhQK7Uf0YCeWggMp2m8TYI',
    appId: '1:875861037228:ios:a88dbad6db7d7e50ff8f09',
    messagingSenderId: '875861037228',
    projectId: 'chat-app-bffb8',
    storageBucket: 'chat-app-bffb8.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
